{
 "title": "MongoDB Cluster Summary",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_instance_uptime_seconds, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mongos Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{job=\"$cluster\", type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{job=\"$cluster\", type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongos  Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connections{job=\"$cluster\", state=\"current\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Mongos  Cursors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_mongod_metrics_cursor_open{job=\"$cluster\", state=\"total\"})",
     "legendFormat": "Cursors"
    }
   ]
  },
  {
   "title": "Operations Per Shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(mongodb_op_counters_total{job=\"$cluster\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{job=\"$cluster\", type!=\"command\"}[5m])) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{job=\"$cluster\"} / mongodb_mongod_replset_my_state{job=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Cursors Per Shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(mongodb_mongod_metrics_cursor_open{job=\"$cluster\", state=\"total\"} or mongodb_mongod_cursors{job=\"$cluster\", state=\"total_open\"}) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{job=\"$cluster\"} / mongodb_mongod_replset_my_state{job=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Connections Per Shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connections{job=\"$cluster\", state=\"current\"} * on (instance) group_right mongodb_mongod_replset_my_state{job=\"$cluster\"}/ mongodb_mongod_replset_my_state{job=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Oplog Range by Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_replset_oplog_head_timestamp{job=\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{job=\"$cluster\"}) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{job=\"$cluster\"} / mongodb_mongod_replset_my_state{job=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Replication Lag by Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(mongodb_mongod_replset_member_optime_date{job=\"$cluster\", state=\"PRIMARY\"}) by (set) - min(mongodb_mongod_replset_member_optime_date{job=\"$cluster\", state=\"SECONDARY\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Collection Lock Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_locks_time_locked_global_microseconds_total{job=\"$cluster\", database=\"Collection\"}) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{job=\"$cluster\"} / mongodb_mongod_replset_my_state{job=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Shard Elections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongo_replset_member_election_date{job=\"$cluster\"}[5m])) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  }
 ]
}