# permissions for end users to view mongodbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodbuser-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongodb-operator
    app.kubernetes.io/part-of: mongodb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodbuser-viewer-role
rules:
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbusers/status
  verbs:
  - get
