# permissions for end users to view mongodbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbcluster-viewer-role
rules:
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbclusters/status
  verbs:
  - get
