
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-operator-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbs/finalizers
  verbs:
  - update
- apiGroups:
  - opstreelabs.in
  resources:
  - mongodbs/status
  verbs:
  - get
  - patch
  - update
