apiVersion: opstreelabs.in/v1alpha1
kind: MongoDBCluster
metadata:
  name: mongodb
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/mongo:v5.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 401m
        memory: 1028Mi
      limits:
        cpu: 401m
        memory: 1028Mi
    securityContext:
      fsGroup: 1001
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 20Gi
#    storageClass: csi-cephfs-sc
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-secret
      key: password
  mongoDBMonitoring:
    enableExporter: true
    image: bitnami/mongodb-exporter:0.11.2-debian-10-r382
    imagePullPolicy: IfNotPresent
  mongoDBAdditionalConfig: mongo-additional-config
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  password: admin_pwd