apiVersion: opstreelabs.in/v1alpha1
kind: MongoDBCluster
metadata:
  name: mongodb
spec:
  clusterSize: 3
  kubernetesConfig:
    image: docker.io/radondb/ot-mongodb:v5.0.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 401m
        memory: 2028Mi
      limits:
        cpu: 401m
        memory: 2028Mi
    securityContext:
      fsGroup: 1001
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 30Gi
#    storageClass: csi-cephfs-sc
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: admin-password-secret
      key: password
  mongoDBMonitoring:
    enableExporter: true
    image: bitnami/mongodb-exporter:0.11.2-debian-10-r382
    imagePullPolicy: IfNotPresent
  mongoDBAdditionalConfig: mongo-additional-config
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongo-ext-cert
      caConfigMapRef:
        name: mongo-ext-ca
#      caCertificateSecretRef:
#        name:
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password-secret
type: Opaque
stringData:
  password: admin_pwd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-additional-config
data:
  mongo.yaml: |
    net.bindIpAll: true
    net.port: 27017
    net.maxIncomingConnections: 20000
    storage.wiredTiger.engineConfig.journalCompressor: zlib  # 数据压缩算法，不可更改
    replication.replSetName: mongodb
    replication.enableMajorityReadConcern: true
    operationProfiling.mode: "off"
    operationProfiling.slowOpThresholdMs: 300
    security.keyFile: /mongo-key/mongo-keyfile
    storage.dbPath: /data/db
    processManagement.pidFilePath: /tmp/mongod.pid
    systemLog.destination: file
    systemLog.path: /data/db/mongod.log
    systemLog.logAppend: true
    systemLog.logRotate: reopen
    systemLog.component.command.verbosity: 0
    systemLog.component.index.verbosity: 0
    systemLog.component.query.verbosity: 0
    systemLog.component.network.verbosity: 0
    systemLog.component.write.verbosity: 0