apiVersion: opstreelabs.in/v1alpha1
kind: MongoDBCluster
metadata:
  name: mongodb
spec:
  clusterSize: 4
  kubernetesConfig:
    image: docker.io/radondb/ot-mongodb:v5.0.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 401m
        memory: 1028Mi
      limits:
        cpu: 401m
        memory: 1028Mi
    securityContext:
      fsGroup: 1001
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 30Gi
#    storageClass: csi-cephfs-sc
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-secret
      key: password
  mongoDBMonitoring:
    enableExporter: true
    image: bitnami/mongodb-exporter:0.11.2-debian-10-r382
    imagePullPolicy: IfNotPresent
  mongoDBAdditionalConfig: mongo-additional-config
  security:
    tls:
      enabled: false
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  password: admin_pwd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-additional-config
data:
  mongo.yaml: |
    net:
      bindIpAll: true
      port: 27017
      maxIncomingConnections: 10000
    storage:
      wiredTiger:
        engineConfig:
          journalCompressor: zlib  # 数据压缩算法，不可更改
    replication:
      replSetName: mongodb
      enableMajorityReadConcern: true
    operationProfiling:
      mode: "off"
      slowOpThresholdMs: 100
    security:
      keyFile: /mongo-key/mongo-keyfile
    storage:
      dbPath: /data/db
    processManagement:
      pidFilePath: /tmp/mongod.pid
    systemLog:
      destination: file
      path: /data/db/mongod.log
      logAppend: true
      logRotate: reopen
      component:
        command:
          verbosity: 0
        index:
          verbosity: 0
        query:
          verbosity: 0
        network:
          verbosity: 0
        write:
          verbosity: 0
    setParameter:
      cursorTimeoutMillis: 700000


