---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-additional-config
data:
  mongo.yaml: |
    net:
      port: 27017
      maxIncomingConnections: 10000
    storage:
      wiredTiger:
        engineConfig:
          journalCompressor: zlib  # 数据压缩算法，不可更改
    replication:
      replSetName: foobar
      enableMajorityReadConcern: true
    operationProfiling:
      mode: "off"
      slowOpThresholdMs: 100
    security:
      keyFile: /mongo-key/mongo-keyfile
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      path: /data/db/mongod.log
      logAppend: true
      logRotate: reopen
      component:
        command:
          verbosity: 0
        index:
          verbosity: 0
        query:
          verbosity: 0
        network:
          verbosity: 0
        write:
          verbosity: 0
    setParameter:
      cursorTimeoutMillis: 700000
