---
apiVersion: opstreelabs.in/v1alpha1
kind: MongoDBCluster
metadata:
  name: mongodb
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/mongo:v5.0
    imagePullPolicy: IfNotPresent
    securityContext:
      fsGroup: 1001
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 1Gi
    storageClass: gp2
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-secret
      key: password
