# ---
# apiVersion: opstreelabs.in/v1alpha1
# kind: MongoDB
# metadata:
#   name: mongodb
# spec:
#   kubernetesConfig:
    
#     image: quay.io/opstree/mongo:v5.0
#     imagePullPolicy: IfNotPresent
#     resources:
#       requests:
#         cpu: 101m 
#         memory: 328Mi 
#       limits:
#         cpu: 101m
#         memory: 328Mi
#   storage:
#     accessModes: ["ReadWriteOnce"]
#     storageSize: 1Gi
#     storageClass: hostpath
#   mongoDBSecurity:
#     mongoDBAdminUser: admin
#     secretRef:
#       name: mongodb-secret
#       key: password

---
apiVersion: opstreelabs.in/v1alpha1
kind: MongoDB
metadata:
  name: mongodb 
spec:
  kubernetesConfig:
    
    image: quay.io/opstree/mongo:v5.0.6 
    imagePullPolicy: IfNotPresent
    nodeSelector: {}
    # affinity: {} 
    tolerations: []
    priorityClassName: ""
    securityContext: 
      fsGroup: 1001
    resources:
      requests:
        cpu: 101m 
        memory: 328Mi  
      limits:
        cpu: 101m
        memory: 328Mi
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 1Gi
    storageClass: civo-volume
  # mongoDBMonitoring:
  #     enableExporter: true
  #     image: quay.io/opstree/mongo:v5.0
  #     imagePullPolicy: IfNotPresent
  #     resources: {}



  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-secret
      key: password
  # mongoDBAdditionalConfig: mongodb-additional-config    
  # mongoDBAdditionalConfig: "./data"  


