---
apiVersion: opstreelabs.in/v1alpha1
kind: MongoDB
metadata:
  name: mongodb-standalone
spec:
  kubernetesConfig:
    image: quay.io/opstree/mongodb:v5.0.5
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
